# Site wide configuration

title:            Bright Inventions
locale:           en_US
avatar:           /images/logo.png
logo: /images/logo.png

defaults:
  -
    scope:
      path: ""
    values:
      image: /images/logo.png

# Jekyll configuration
url: https://brightinventions.pl
github_repo_url: https://github.com/bright/new-www/
permalink:   /blog/:categories/:title/
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Site owner
owner:
  name: Software Development Company | Bright Inventionss
  bio: "Bright Inventions is a team of excellent developers dedicated to delivering first-rate mobile platforms. Since our founding in 2011 we've worked with clients from a range of industries with diverse requirements always delivering high quality mobile solutions that they can depend on."
  email: info@brightinventions.pl
  disqus-shortname: brightinventions
  twitter: BrightDevs
  facebook: Bright.Inventions
  google:
    plus: #username
    analytics: 'UA-56513184-1'
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: bright
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: bright_devs
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", ".git"]

paginate: 10
paginate_path: "/blog/page-:num/"

twitter:
  username: BrightDevs

facebook:
  publisher: https://www.facebook.com/Bright.Inventions/

social:
  name: Bright Inventions
  links:
    - https://www.facebook.com/Bright.Inventions/
    - https://twitter.com/brightdevs
    - https://www.instagram.com/bright_inventions/
    - https://stackoverflow.com/jobs/companies/bright-inventions
