backend:
  name: github
  repo: bright/new-www
  branch: gh-pages
  base_url: https://github-auth.brightinventions.pl
media_folder: "images"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hidden", name: "hidden", widget: "boolean", default: "false"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Tags", name: "tags", widget: "select", create: "true", selectFrom: {collection: "posts", field: "tags"}}
      - {label: "Author", name: "author", widget: "select", selectFrom: {collection: "members", field: "id"}}
      - {label: "Body", name: "body", widget: "markdown"}
