name: Gatsby Publish

on:
  push:
    branches:
      - gatsby

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - run: yarn run build
      - run: 7z a content.zip public/
      - name: Archive content
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}-content.zip
          path: content.zip
      - name: Archive .cache/s3.config.json
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}-s3.config.json
          path: .cache/s3.config.json
  deploy-gh-pages:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Download archive content
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.sha }}-content.zip
          path: content.zip
      - run: 7z x content.zip public/
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
  deploy-s3:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Download archive content
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.sha }}-content.zip
          path: content.zip
      - name: Download .cache/s3.config.json
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.sha }}-s3.config.json
          path: .cache/s3.config.json
      - run: 7z x content.zip public/
      - run: ls -alh public/
      - run: yarn install
      - run: yarn run deploy-s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY_SECRET: ${{ secrets.AWS_ACCESS_KEY_SECRET }}

